# Generated by Django 3.1.7 on 2021-06-16 20:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Menu_Item',
                'verbose_name_plural': ' Menu_Item',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('has_confirmed_by_user', models.BooleanField(default=False, null=True)),
                ('has_confirmed_by_waiter', models.BooleanField(default=False, null=True)),
                ('has_confirmed_by_cheif', models.BooleanField(default=False, null=True)),
                ('has_been_delivered', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='oredr_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('oreder_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_orders.menu_item', verbose_name='oreder_item')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuupdates',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='menuupdates',
            name='updated_fields',
        ),
        migrations.RemoveField(
            model_name='menuupdates',
            name='updated_menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='updates',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='Table_Menu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Table_Menu', to='app_orders.menu'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='MenuFields',
        ),
        migrations.DeleteModel(
            name='MenuUpdates',
        ),
        migrations.AddField(
            model_name='order',
            name='oreder_item',
            field=models.ManyToManyField(to='app_orders.oredr_item', verbose_name='oreder_item'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.table', verbose_name='table'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(related_name='menu_items', to='app_orders.Menu_Item', verbose_name='menu_items'),
        ),
    ]
