# Generated by Django 3.1.7 on 2021-06-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_auto_20210616_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='has_been_delivered',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_confirmed_by_cheif',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_confirmed_by_user',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_confirmed_by_waiter',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
