# Generated by Django 3.1.7 on 2021-06-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_order_has_been_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_item',
            options={'verbose_name': ' Menu_Item', 'verbose_name_plural': ' Menu_Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
        migrations.AlterModelOptions(
            name='oredr_item',
            options={'verbose_name': 'order_item', 'verbose_name_plural': 'order_item'},
        ),
        migrations.RemoveField(
            model_name='table',
            name='Table_Menu',
        ),
        migrations.AddField(
            model_name='table',
            name='menu_items',
            field=models.ManyToManyField(related_name='menu_items', to='app_orders.Menu_Item', verbose_name='menu_items'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
