# Generated by Django 3.1.7 on 2021-06-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_auto_20210628_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='menu_items',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, null=True)),
                ('menu_items', models.ManyToManyField(related_name='menu_items', to='app_orders.Menu_Item', verbose_name='menu_items')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='Table_Menu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Table_Menu', to='app_orders.menu'),
        ),
    ]
