# Generated by Django 3.1.7 on 2021-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0006_auto_20210628_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oreder_item',
            field=models.ManyToManyField(to='app_orders.Oredr_Item', verbose_name='oreder_item'),
        ),
    ]
