# Generated by Django 3.1.7 on 2021-06-30 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_auto_20210630_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_orders.menu_item', verbose_name='food_item')),
            ],
            options={
                'verbose_name': 'order_item',
                'verbose_name_plural': 'order_item',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='oreder_item',
        ),
        migrations.DeleteModel(
            name='oredr_item',
        ),
        migrations.AddField(
            model_name='order',
            name='order_food_item',
            field=models.ManyToManyField(to='app_orders.Order_Item', verbose_name='order_food_item '),
        ),
    ]
