# Generated by Django 3.1.7 on 2021-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0009_menu_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='kitchen_type',
            field=models.CharField(choices=[('kitchen 1', 'drinks'), ('kitchen 2', 'arabic food'), ('kitchen 3', 'western food')], max_length=50, null=True),
        ),
    ]
