# Generated by Django 3.1.7 on 2021-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0010_menu_item_kitchen_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_been_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='has_confirmed_by_cheif',
        ),
        migrations.AddField(
            model_name='order_item',
            name='has_been_delivered',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='order_item',
            name='has_confirmed_by_cheif',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
