# Generated by Django 3.1.7 on 2021-07-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0011_auto_20210728_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
