# Generated by Django 3.1.7 on 2021-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0012_order_item_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'available'), ('2', ' come to finished '), ('3', ' finished')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
    ]
