# Generated by Django 3.2.4 on 2021-08-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0013_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='category_type',
            field=models.CharField(choices=[('category 1', 'pizza'), ('category 2', ' steak'), ('category 3', ' burger'), ('category 4', ' juice'), ('category 5', ' rice'), ('category 6', ' pasta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
